name=OFC_Setup_process
version=1.0.0
author=Nathan Lebrun
maintainer=Nathan Lebrun <contact@nalebrun.be>
sentence=Setup process abstraction. (only usefull in this project)
paragraph=manage setup process
category=Other
architectures=*
