name=OFC_Network
version=1.0.0
author=Nathan Lebrun
maintainer=Nathan Lebrun <contact@nalebrun.be>
sentence=Network abstraction. (only usefull in this project)
paragraph=manage wifi, AP, API calls
category=Other
architectures=*
